# Generated by Django 3.0.5 on 2020-04-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(max_length=20)),
                ('sFee', models.IntegerField()),
                ('sPhoto', models.ImageField(upload_to='')),
            ],
        ),
    ]
